apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node-rc
  labels:
    app: chrome-node-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-node-rc
  template:
    metadata:
      name: chrome-node-rc
      labels:
        app: chrome-node-rc
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: chrome-node-rc
          image: 'selenium/node-chrome-debug:3.141'
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: HUB_HOST
              value: 13.86.140.82
            - name: HUB_PORT
              value: '4444'
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
